name: Run Workflow
on:
  repository_dispatch:
    types: [run-workflow]

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print message
        run: echo "Привет"
      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: run python
        run: python3 main.py